// Comprehensive emoji name mappings for search
// This allows users to search for emojis by their common names
export const EMOJI_NAMES: Record<string, string[]> = {
  // Smileys & People
  "😀": ["happy", "grinning", "smile", "face"],
  "😃": ["happy", "grinning", "eyes", "smile"],
  "😄": ["happy", "grinning", "eyes", "smile", "laugh"],
  "😁": ["beaming", "smile", "happy"],
  "😆": ["laughing", "squinting", "happy"],
  "😅": ["sweat", "smile", "relieved"],
  "😂": ["laughing", "tears", "joy", "funny"],
  "🤣": ["rolling", "floor", "laughing", "funny"],
  "😊": ["smiling", "eyes", "happy", "blush"],
  "😇": ["halo", "angel", "innocent"],
  "🙂": ["slightly", "smiling", "face"],
  "🙃": ["upside", "down", "face"],
  "😉": ["wink", "winking", "face"],
  "😌": ["relieved", "face"],
  "😍": ["heart", "eyes", "love", "like"],
  "🥰": ["smiling", "hearts", "love"],
  "😘": ["kiss", "blowing", "kiss"],
  "😗": ["kissing", "face"],
  "😙": ["kissing", "smiling", "eyes"],
  "😚": ["kissing", "closed", "eyes"],
  "😋": ["yum", "delicious", "food"],
  "😛": ["tongue", "face"],
  "😝": ["squinting", "tongue", "wink"],
  "😜": ["wink", "tongue", "playful"],
  "🤪": ["zany", "crazy", "face"],
  "🤨": ["raised", "eyebrow", "suspicious"],
  "🧐": ["monocle", "detective", "investigating"],
  "🤓": ["nerd", "glasses", "smart"],
  "😎": ["sunglasses", "cool", "shades"],
  "🤩": ["star", "eyes", "excited"],
  "🥳": ["party", "celebration", "birthday"],
  "😏": ["smirking", "face"],
  "😒": ["unamused", "face"],
  "😞": ["disappointed", "sad"],
  "😔": ["sad", "pensive"],
  "😟": ["worried", "face"],
  "😕": ["slightly", "frowning", "face"],
  "🙁": ["frowning", "face"],
  "😣": ["persevering", "face"],
  "😖": ["confounded", "face"],
  "😫": ["tired", "face"],
  "😩": ["weary", "face"],
  "🥺": ["pleading", "puppy", "eyes"],
  "😢": ["crying", "face", "tears"],
  "😭": ["loudly", "crying", "tears"],
  "😤": ["triumph", "face"],
  "😠": ["angry", "face"],
  "😡": ["pouting", "angry", "face"],
  "🤬": ["swearing", "cursing", "face"],
  "🤯": ["exploding", "head", "mind", "blown"],
  "😳": ["flushed", "face", "embarrassed"],
  "🥵": ["hot", "face", "sweating"],
  "🥶": ["cold", "face", "freezing"],
  "😱": ["scream", "fear", "face"],
  "😨": ["fearful", "face"],
  "😰": ["anxious", "sweat", "face"],
  "😥": ["sad", "relieved", "face"],
  "😓": ["downcast", "sweat", "face"],
  "🤗": ["hugging", "face"],
  "🤔": ["thinking", "face"],
  "🤭": ["hand", "mouth", "shushing"],
  "🤫": ["shushing", "quiet", "face"],
  "🤥": ["lying", "face", "pinocchio"],
  "😶": ["face", "no", "mouth"],
  "😐": ["neutral", "face"],
  "😑": ["expressionless", "face"],
  "😬": ["grimacing", "face"],
  "🙄": ["rolling", "eyes"],
  "😯": ["hushed", "face"],
  "😦": ["frowning", "open", "mouth"],
  "😧": ["anguished", "face"],
  "😮": ["open", "mouth", "face"],
  "😲": ["astonished", "face"],
  "🥱": ["yawning", "face", "tired"],
  "😴": ["sleeping", "face", "tired"],
  "🤤": ["drooling", "face"],
  "😪": ["sleepy", "face", "tired"],
  "😵": ["dizzy", "face"],
  "🤐": ["zipper", "mouth", "face"],
  "🥴": ["woozy", "face", "dizzy"],
  "🤢": ["nauseated", "face", "sick"],
  "🤮": ["vomiting", "face", "sick"],
  "🤧": ["sneezing", "face", "sick"],
  "😷": ["medical", "mask", "sick"],
  "🤒": ["thermometer", "face", "sick"],
  "🤕": ["bandaged", "head", "injured"],
  "🤑": ["money", "mouth", "face", "rich"],
  "🤠": ["cowboy", "hat", "face"],
  "😈": ["smiling", "devil", "horns"],
  "👿": ["angry", "devil", "horns"],
  "👹": ["ogre", "monster", "japanese"],
  "👺": ["goblin", "monster", "japanese"],
  "🤡": ["clown", "face"],
  "💩": ["poop", "poo", "face"],
  "👻": ["ghost", "spooky"],
  "💀": ["skull", "death"],
  "☠️": ["skull", "crossbones", "death"],
  "👽": ["alien", "extraterrestrial"],
  "👾": ["alien", "monster", "space"],
  "🤖": ["robot", "bot"],
  "🎃": ["jack", "o", "lantern", "halloween"],
  "😺": ["grinning", "cat", "face"],
  "😸": ["grinning", "cat", "eyes"],
  "😹": ["joy", "cat", "tears"],
  "😻": ["heart", "eyes", "cat"],
  "😼": ["smirk", "cat"],
  "😽": ["kissing", "cat"],
  "🙀": ["weary", "cat"],
  "😿": ["crying", "cat", "face"],
  "😾": ["pouting", "cat"],

  // Gestures
  "👋": ["waving", "hand", "hello", "hi", "bye"],
  "🤚": ["raised", "back", "hand"],
  "🖐": ["hand", "fingers", "splayed"],
  "✋": ["raised", "hand", "stop"],
  "🖖": ["vulcan", "salute", "spock"],
  "👌": ["ok", "hand", "perfect"],
  "🤏": ["pinching", "hand"],
  "✌️": ["victory", "peace", "hand"],
  "🤞": ["crossed", "fingers", "luck"],
  "🤟": ["love", "you", "gesture"],
  "🤘": ["rock", "on", "horns"],
  "🤙": ["call", "me", "hand"],
  "👈": ["pointing", "left"],
  "👉": ["pointing", "right"],
  "👆": ["pointing", "up"],
  "🖕": ["middle", "finger"],
  "👇": ["pointing", "down"],
  "☝️": ["index", "pointing", "up"],
  "👍": ["thumbs", "up", "like", "good", "yes"],
  "👎": ["thumbs", "down", "dislike", "bad", "no"],
  "✊": ["raised", "fist"],
  "👊": ["oncoming", "fist", "punch"],
  "🤛": ["left", "facing", "fist"],
  "🤜": ["right", "facing", "fist"],
  "👏": ["clapping", "hands", "applause"],
  "🙌": ["raising", "hands", "celebration"],
  "👐": ["open", "hands"],
  "🤲": ["palms", "together"],
  "🤝": ["handshake"],
  "🙏": ["folded", "hands", "pray", "please"],
  "✍️": ["writing", "hand"],
  "💪": ["flexed", "biceps", "strong", "muscle"],
  "🦾": ["mechanical", "arm"],
  "🦿": ["mechanical", "leg"],
  "🦵": ["leg"],
  "🦶": ["foot"],
  "👂": ["ear"],
  "🦻": ["ear", "hearing", "aid"],
  "👃": ["nose"],
  "🧠": ["brain"],
  "🦷": ["tooth"],
  "🦴": ["bone"],
  "👀": ["eyes"],
  "👁️": ["eye"],
  "👅": ["tongue"],
  "👄": ["mouth", "lips"],

  // Objects
  "💍": ["ring", "jewelry", "diamond"],
  "👑": ["crown", "king", "queen"],
  "👒": ["womans", "hat"],
  "🎩": ["top", "hat"],
  "🎓": ["graduation", "cap"],
  "🧢": ["billed", "cap"],
  "⛑️": ["rescue", "workers", "helmet"],
  "📿": ["prayer", "beads"],
  "💄": ["lipstick"],
  "💎": ["gem", "diamond"],
  "🔇": ["muted", "speaker"],
  "🔈": ["speaker", "low", "volume"],
  "🔉": ["speaker", "medium", "volume"],
  "🔊": ["speaker", "high", "volume"],
  "📢": ["megaphone", "loudspeaker"],
  "📣": ["megaphone"],
  "📯": ["postal", "horn"],
  "🔔": ["bell"],
  "🔕": ["bell", "slash", "muted"],
  "🎼": ["musical", "score"],
  "🎵": ["musical", "note"],
  "🎶": ["musical", "notes"],
  "🎙️": ["studio", "microphone"],
  "🎚️": ["level", "slider"],
  "🎛️": ["control", "knobs"],
  "🎤": ["microphone", "mic"],
  "🎧": ["headphone"],
  "📻": ["radio"],
  "🎷": ["saxophone"],
  "🎺": ["trumpet"],
  "🎸": ["guitar"],
  "🎻": ["violin"],
  "🎹": ["piano", "keyboard"],
  "🥁": ["drum"],
  "🎲": ["dice", "game"],
  "🎯": ["target", "dart", "goal"],
  "🎳": ["bowling"],
  "🎮": ["video", "game", "controller"],
  "🎰": ["slot", "machine"],
  "🧩": ["puzzle", "piece"],

  // Symbols
  "❤️": ["red", "heart", "love", "like"],
  "🧡": ["orange", "heart"],
  "💛": ["yellow", "heart"],
  "💚": ["green", "heart"],
  "💙": ["blue", "heart"],
  "💜": ["purple", "heart"],
  "🖤": ["black", "heart"],
  "🤍": ["white", "heart"],
  "🤎": ["brown", "heart"],
  "💔": ["broken", "heart"],
  "❣️": ["heart", "exclamation"],
  "💕": ["two", "hearts"],
  "💞": ["revolving", "hearts"],
  "💓": ["beating", "heart"],
  "💗": ["growing", "heart"],
  "💖": ["sparkling", "heart"],
  "💘": ["heart", "arrow", "cupid"],
  "💝": ["heart", "ribbon", "gift"],
  "💟": ["heart", "decoration"],
  "☮️": ["peace", "symbol"],
  "✝️": ["latin", "cross"],
  "☪️": ["star", "crescent"],
  "🕉️": ["om"],
  "☸️": ["wheel", "dharma"],
  "✡️": ["star", "david"],
  "🔯": ["dotted", "six", "pointed", "star"],
  "🕎": ["menorah"],
  "☯️": ["yin", "yang"],
  "☦️": ["orthodox", "cross"],
  "🛐": ["place", "worship"],
  "⛎": ["ophiuchus"],
  "♈": ["aries"],
  "♉": ["taurus"],
  "♊": ["gemini"],
  "♋": ["cancer"],
  "♌": ["leo"],
  "♍": ["virgo"],
  "♎": ["libra"],
  "♏": ["scorpio"],
  "♐": ["sagittarius"],
  "♑": ["capricorn"],
  "♒": ["aquarius"],
  "♓": ["pisces"],
  "🆔": ["id", "button"],
  "⚛️": ["atom", "symbol"],
  "🉑": ["japanese", "acceptable", "button"],
  "☢️": ["radioactive"],
  "☣️": ["biohazard"],

  // Activities
  "⚽": ["soccer", "football"],
  "🏀": ["basketball"],
  "🏈": ["american", "football"],
  "⚾": ["baseball"],
  "🥎": ["softball"],
  "🎾": ["tennis"],
  "🏐": ["volleyball"],
  "🏉": ["rugby", "football"],
  "🥏": ["flying", "disc", "frisbee"],
  "🎱": ["pool", "8", "ball"],
  "🏓": ["ping", "pong", "table", "tennis"],
  "🏸": ["badminton"],
  "🥅": ["goal", "net"],
  "🏒": ["ice", "hockey"],
  "🏑": ["field", "hockey"],
  "🏏": ["cricket"],
  "🥍": ["lacrosse"],
  "🏹": ["bow", "arrow"],
  "🎣": ["fishing", "pole"],
  "🥊": ["boxing", "glove"],
  "🥋": ["martial", "arts", "uniform"],
  "🎽": ["running", "shirt"],
  "🛹": ["skateboard"],
  "🛷": ["sled"],
  "⛸️": ["ice", "skate"],
  "🥌": ["curling", "stone"],
  "🎿": ["skis"],
  "⛷️": ["skier"],
  "🏂": ["snowboarder"],
  "🏋️": ["weight", "lifter"],
  "🤼": ["wrestlers"],
  "🤸": ["person", "cartwheeling"],
  "🤺": ["fencer"],
  "⛹️": ["person", "bouncing", "ball"],
  "🤹": ["juggling"],
  "🧘": ["person", "lotus", "position", "meditation"],
  "🏌️": ["golfer"],
  "🏇": ["horse", "racing"],
  "🧗": ["climber"],
  "🚵": ["mountain", "biker"],
  "🚴": ["cyclist"],
  "🏆": ["trophy"],
  "🥇": ["1st", "place", "medal", "gold"],
  "🥈": ["2nd", "place", "medal", "silver"],
  "🥉": ["3rd", "place", "medal", "bronze"],
  "🏅": ["sports", "medal"],
  "🎖️": ["military", "medal"],
  "🏵️": ["rosette"],
  "🎗️": ["reminder", "ribbon"],
  "🎫": ["ticket"],
  "🎟️": ["admission", "tickets"],
  "🎪": ["circus", "tent"],
  "🎭": ["performing", "arts"],
  "🩰": ["ballet", "shoes"],
  "🎨": ["artist", "palette"],
  "🎬": ["clapper", "board"],
  "🎤": ["microphone", "mic"],
  "🎧": ["headphone"],
  "🎼": ["musical", "score"],
  "🎹": ["piano", "keyboard"],
  "🥁": ["drum"],
  "🎷": ["saxophone"],
  "🎺": ["trumpet"],
  "🎸": ["guitar"],
  "🎻": ["violin"],
  "🎲": ["dice", "game"],
  "🎯": ["target", "dart", "goal"],
  "🎳": ["bowling"],
  "🎮": ["video", "game", "controller"],
  "🎰": ["slot", "machine"],
  "🚗": ["car", "automobile"],
  "🚕": ["taxi"],
  "🚙": ["suv"],
  "🚌": ["bus"],
  "🚎": ["trolleybus"],
  "🏎️": ["racing", "car"],
  "🚓": ["police", "car"],
  "🚑": ["ambulance"],
  "🚒": ["fire", "engine"],
  "🚐": ["minibus"],
  "🚚": ["delivery", "truck"],
  "🚛": ["articulated", "lorry"],
  "🚜": ["tractor"],
  "🛴": ["kick", "scooter"],
  "🚲": ["bicycle", "bike"],
  "🛵": ["motor", "scooter"],
  "🏍️": ["motorcycle"],
  "🛺": ["auto", "rickshaw"],
  "🚨": ["police", "car", "light"],
  "🚔": ["oncoming", "police", "car"],
  "🚍": ["oncoming", "bus"],
  "🚘": ["oncoming", "automobile"],
  "🚖": ["oncoming", "taxi"],
  "🚡": ["aerial", "tramway"],
  "🚠": ["mountain", "cableway"],
  "🚟": ["suspension", "railway"],
  "🚃": ["tram", "car"],
  "🚋": ["tram"],
  "🚞": ["mountain", "railway"],
  "🚝": ["monorail"],
  "🚄": ["high", "speed", "train"],
  "🚅": ["bullet", "train"],
  "🚈": ["light", "rail"],
  "🚂": ["locomotive", "steam", "train"],
  "🚆": ["train"],
  "🚇": ["metro", "subway"],
  "🚊": ["tram"],
  "🚉": ["station"],
  "✈️": ["airplane"],
  "🛫": ["airplane", "departure"],
  "🛬": ["airplane", "arrival"],
  "🛩️": ["small", "airplane"],
  "💺": ["seat"],
  "🚁": ["helicopter"],
  "🛰️": ["satellite"],
  "🚀": ["rocket", "launch", "space"],
  "🛸": ["flying", "saucer", "ufo"],
  "🛎️": ["bellhop", "bell"],
  "🧳": ["luggage"],

  // Food & Drink
  "🍏": ["green", "apple"],
  "🍎": ["red", "apple"],
  "🍐": ["pear"],
  "🍊": ["tangerine", "orange"],
  "🍋": ["lemon"],
  "🍌": ["banana"],
  "🍉": ["watermelon"],
  "🍇": ["grapes"],
  "🍓": ["strawberry"],
  "🍈": ["melon"],
  "🍒": ["cherries"],
  "🍑": ["peach"],
  "🥭": ["mango"],
  "🍍": ["pineapple"],
  "🥥": ["coconut"],
  "🥝": ["kiwi", "fruit"],
  "🍅": ["tomato"],
  "🍆": ["eggplant", "aubergine"],
  "🥑": ["avocado"],
  "🥦": ["broccoli"],
  "🥬": ["leafy", "green"],
  "🥒": ["cucumber"],
  "🌶️": ["hot", "pepper"],
  "🌽": ["corn", "ear"],
  "🥕": ["carrot"],
  "🥔": ["potato"],
  "🍠": ["sweet", "potato", "roasted"],
  "🥐": ["croissant"],
  "🥯": ["bagel"],
  "🍞": ["bread", "loaf"],
  "🥖": ["baguette", "bread"],
  "🥨": ["pretzel"],
  "🧀": ["cheese", "wedge"],
  "🥚": ["egg"],
  "🍳": ["cooking", "fried", "egg"],
  "🥞": ["pancakes"],
  "🥓": ["bacon"],
  "🥩": ["meat", "bone"],
  "🍗": ["poultry", "leg"],
  "🍖": ["meat", "bone"],
  "🌭": ["hot", "dog"],
  "🍔": ["hamburger", "burger"],
  "🍟": ["french", "fries"],
  "🍕": ["pizza", "slice"],
  "🥪": ["sandwich"],
  "🥫": ["canned", "food"],
  "🌮": ["taco"],
  "🌯": ["burrito"],
  "🥙": ["stuffed", "flatbread"],
  "🥘": ["shallow", "pan", "food"],
  "🍲": ["pot", "food"],
  "🥣": ["bowl", "spoon"],
  "🥗": ["green", "salad"],
  "🍿": ["popcorn"],
  "🧂": ["salt"],
  "🍱": ["bento", "box"],
  "🍘": ["rice", "cracker"],
  "🍙": ["rice", "ball"],
  "🍚": ["cooked", "rice"],
  "🍛": ["curry", "rice"],
  "🍜": ["steaming", "bowl"],
  "🍝": ["spaghetti"],
  "🍢": ["oden"],
  "🍣": ["sushi"],
  "🍤": ["fried", "shrimp"],
  "🍥": ["fish", "cake", "swirl"],
  "🥮": ["moon", "cake"],
  "🍡": ["dango"],
  "🥟": ["dumpling"],
  "🥠": ["fortune", "cookie"],
  "🥡": ["takeout", "box"],
  "🍦": ["soft", "ice", "cream"],
  "🍧": ["shaved", "ice"],
  "🍨": ["ice", "cream"],
  "🍩": ["doughnut"],
  "🍪": ["cookie"],
  "🎂": ["birthday", "cake"],
  "🍰": ["shortcake", "cake"],
  "🧁": ["cupcake"],
  "🥧": ["pie"],
  "🍫": ["chocolate", "bar"],
  "🍬": ["candy"],
  "🍭": ["lollipop"],
  "🍮": ["custard"],
  "🍯": ["honey", "pot"],
  "🍼": ["baby", "bottle"],
  "🥛": ["glass", "milk"],
  "☕": ["hot", "beverage", "coffee", "tea"],
  "🍵": ["teacup", "without", "handle"],
  "🍶": ["sake", "bottle", "cup"],
  "🍾": ["bottle", "popping", "cork", "champagne"],
  "🍷": ["wine", "glass"],
  "🍸": ["cocktail", "glass"],
  "🍹": ["tropical", "drink"],
  "🍺": ["beer", "mug"],
  "🍻": ["clinking", "beer", "mugs"],
  "🥂": ["clinking", "glasses"],
  "🥃": ["tumbler", "glass"],
  "🥤": ["cup", "straw"],
  "🧃": ["beverage", "box"],
  "🧉": ["mate"],
  "🧊": ["ice"],

  // Nature
  "🐶": ["dog", "face", "puppy"],
  "🐱": ["cat", "face", "kitten"],
  "🐭": ["mouse", "face"],
  "🐹": ["hamster", "face"],
  "🐰": ["rabbit", "face", "bunny"],
  "🦊": ["fox", "face"],
  "🐻": ["bear", "face"],
  "🐼": ["panda", "face"],
  "🐨": ["koala"],
  "🐯": ["tiger", "face"],
  "🦁": ["lion", "face"],
  "🐮": ["cow", "face"],
  "🐷": ["pig", "face"],
  "🐽": ["pig", "nose"],
  "🐸": ["frog", "face"],
  "🐵": ["monkey", "face"],
  "🙈": ["see", "no", "evil", "monkey"],
  "🙉": ["hear", "no", "evil", "monkey"],
  "🙊": ["speak", "no", "evil", "monkey"],
  "🐒": ["monkey"],
  "🐔": ["chicken"],
  "🐧": ["penguin"],
  "🐦": ["bird"],
  "🐤": ["baby", "chick"],
  "🐣": ["hatching", "chick"],
  "🐥": ["front", "facing", "baby", "chick"],
  "🦆": ["duck"],
  "🦅": ["eagle"],
  "🦉": ["owl"],
  "🦇": ["bat"],
  "🐺": ["wolf", "face"],
  "🐗": ["boar"],
  "🐴": ["horse", "face"],
  "🦄": ["unicorn", "face"],
  "🐝": ["honeybee"],
  "🐛": ["bug"],
  "🦋": ["butterfly"],
  "🐌": ["snail"],
  "🐞": ["lady", "beetle"],
  "🐜": ["ant"],
  "🦟": ["mosquito"],
  "🦗": ["cricket"],
  "🕷️": ["spider"],
  "🕸️": ["spider", "web"],
  "🦂": ["scorpion"],
  "🐢": ["turtle"],
  "🐍": ["snake"],
  "🦎": ["lizard"],
  "🦖": ["t", "rex"],
  "🦕": ["sauropod"],
  "🐙": ["octopus"],
  "🦑": ["squid"],
  "🦐": ["shrimp"],
  "🦞": ["lobster"],
  "🦀": ["crab"],
  "🐡": ["blowfish"],
  "🐠": ["tropical", "fish"],
  "🐟": ["fish"],
  "🐬": ["dolphin"],
  "🐳": ["spouting", "whale"],
  "🐋": ["whale"],
  "🦈": ["shark"],
  "🐊": ["crocodile"],
  "🐅": ["tiger"],
  "🐆": ["leopard"],
  "🦓": ["zebra"],
  "🦍": ["gorilla"],
  "🦧": ["orangutan"],
  "🐘": ["elephant"],
  "🦛": ["hippopotamus"],
  "🦏": ["rhinoceros"],
  "🐪": ["dromedary", "camel"],
  "🐫": ["bactrian", "camel"],
  "🦒": ["giraffe"],
  "🦘": ["kangaroo"],
  "🦡": ["badger"],
  "🐃": ["water", "buffalo"],
  "🐂": ["ox"],
  "🐄": ["cow"],
  "🐎": ["horse"],
  "🐖": ["pig"],
  "🐏": ["ram"],
  "🐑": ["ewe", "sheep"],
  "🦙": ["llama"],
  "🐐": ["goat"],
  "🦌": ["deer"],
  "🐕": ["dog"],
  "🐩": ["poodle"],
  "🐈": ["cat"],
  "🐓": ["rooster"],
  "🦃": ["turkey"],
  "🦢": ["swan"],
  "🦚": ["peacock"],
  "🦜": ["parrot"],
  "🐇": ["rabbit"],
  "🦝": ["raccoon"],
  "🦨": ["skunk"],
  "🦦": ["otter"],
  "🦥": ["sloth"],
  "🐁": ["mouse"],
  "🐀": ["rat"],
  "🐿️": ["chipmunk"],
  "🦔": ["hedgehog"],
  "🌲": ["evergreen", "tree"],
  "🌳": ["deciduous", "tree"],
  "🌴": ["palm", "tree"],
  "🌵": ["cactus"],
  "🌷": ["tulip"],
  "🌹": ["rose"],
  "🥀": ["wilted", "flower"],
  "🌺": ["hibiscus"],
  "🌻": ["sunflower"],
  "🌼": ["blossom"],
  "🌾": ["sheaf", "rice"],
  "🌿": ["herb"],
  "☘️": ["shamrock"],
  "🍀": ["four", "leaf", "clover"],
  "🍁": ["maple", "leaf"],
  "🍂": ["fallen", "leaf"],
  "🍃": ["leaf", "fluttering", "wind"],
  "🍄": ["mushroom"],
  "🌰": ["chestnut"],
  "🌱": ["seedling"],
  "🌍": ["globe", "showing", "europe", "africa"],
  "🌎": ["globe", "showing", "americas"],
  "🌏": ["globe", "showing", "asia", "australia"],
  "🌐": ["globe", "meridians"],
  "🗾": ["map", "japan"],
  "🗺️": ["world", "map"],
  "🧭": ["compass"],
  "🏔️": ["snow", "capped", "mountain"],
  "⛰️": ["mountain"],
  "🌋": ["volcano"],
  "🗻": ["mount", "fuji"],
  "🏕️": ["camping"],
  "🏖️": ["beach", "umbrella"],
  "🏜️": ["desert"],
  "🏝️": ["desert", "island"],
  "🏞️": ["national", "park"],
  "🏟️": ["stadium"],
  "🏛️": ["classical", "building"],
  "🏗️": ["building", "construction"],
  "🧱": ["brick"],
  "🏘️": ["houses"],
  "🏚️": ["derelict", "house"],
  "🏠": ["house"],
  "🏡": ["house", "garden"],
  "🏢": ["office", "building"],
  "🏣": ["japanese", "post", "office"],
  "🏤": ["post", "office"],
  "🏥": ["hospital"],
  "🏦": ["bank"],
  "🏨": ["hotel"],
  "🏩": ["love", "hotel"],
  "🏪": ["convenience", "store"],
  "🏫": ["school"],
  "🏬": ["department", "store"],
  "🏭": ["factory"],
  "🏯": ["japanese", "castle"],
  "🏰": ["castle"],
  "💒": ["wedding"],
  "🗼": ["tokyo", "tower"],
  "🗽": ["statue", "liberty"],
  "⛪": ["church"],
  "🕌": ["mosque"],
  "🛕": ["hindu", "temple"],
  "🕍": ["synagogue"],
  "⛩️": ["shinto", "shrine"],
  "🕋": ["kaaba"],
  "⛲": ["fountain"],
  "⛺": ["tent"],
  "🌁": ["foggy"],
  "🌃": ["night", "stars"],
  "🏙️": ["cityscape"],
  "🌄": ["sunrise", "mountains"],
  "🌅": ["sunrise"],
  "🌆": ["cityscape", "dusk"],
  "🌇": ["sunset"],
  "🌉": ["bridge", "night"],
  "♨️": ["hot", "springs"],
  "🎠": ["carousel", "horse"],
  "🎡": ["ferris", "wheel"],
  "🎢": ["roller", "coaster"],
  "💈": ["barber", "pole"],
  "🎪": ["circus", "tent"],
  "🚂": ["locomotive", "steam", "train"],
  "🚃": ["tram", "car"],
  "🚄": ["high", "speed", "train"],
  "🚅": ["bullet", "train"],
  "🚆": ["train"],
  "🚇": ["metro", "subway"],
  "🚈": ["light", "rail"],
  "🚉": ["station"],
  "🚊": ["tram"],
  "🚝": ["monorail"],
  "🚞": ["mountain", "railway"],
  "🚟": ["suspension", "railway"],
  "🚠": ["mountain", "cableway"],
  "🚡": ["aerial", "tramway"],
  "🛤️": ["railway", "track"],
  "🛣️": ["motorway"],
  "🗺️": ["world", "map"],
  "🗿": ["moai"],
  "🗽": ["statue", "liberty"],
  "🗼": ["tokyo", "tower"],
  "🏰": ["castle"],
  "⛩️": ["shinto", "shrine"],
  "🕍": ["synagogue"],
  "🕌": ["mosque"],
  "🛕": ["hindu", "temple"],
  "⛪": ["church"],
  "💒": ["wedding"],
  "🏛️": ["classical", "building"],
  "⛲": ["fountain"],
  "⛺": ["tent"],
  "🌁": ["foggy"],
  "🌃": ["night", "stars"],
  "🌄": ["sunrise", "mountains"],
  "🌅": ["sunrise"],
  "🌆": ["cityscape", "dusk"],
  "🌇": ["sunset"],
  "🌉": ["bridge", "night"],
  "♨️": ["hot", "springs"],
  "🎠": ["carousel", "horse"],
  "🛎️": ["bellhop", "bell"],
  "🚪": ["door"],
  "🛏️": ["bed"],
  "🛋️": ["couch", "lamp"],
  "🚽": ["toilet"],
  "🚿": ["shower"],
  "🛁": ["bathtub"],
  "🧴": ["lotion", "bottle"],
  "🧷": ["safety", "pin"],
  "🧹": ["broom"],
  "🧺": ["basket"],
  "🧻": ["roll", "paper"],
  "🧼": ["soap"],
  "🧽": ["sponge"],
  "🧯": ["fire", "extinguisher"],
  "🛒": ["shopping", "cart"],
  "🚬": ["cigarette"],
  "⚰️": ["coffin"],
  "⚱️": ["funeral", "urn"],
  "🗿": ["moai"],
  "🏧": ["atm", "sign"],
  "🚮": ["litter", "bin", "sign"],
  "🚰": ["potable", "water"],
  "♿": ["wheelchair", "symbol"],
  "🚹": ["mens", "room"],
  "🚺": ["womens", "room"],
  "🚻": ["restroom"],
  "🚼": ["baby", "symbol"],
  "🚾": ["water", "closet"],
  "🛂": ["passport", "control"],
  "🛃": ["customs"],
  "🛄": ["baggage", "claim"],
  "🛅": ["left", "luggage"],
  "⚠️": ["warning", "sign", "caution"],
  "🚸": ["children", "crossing"],
  "⛔": ["no", "entry"],
  "🚫": ["prohibited"],
  "🚳": ["no", "bicycles"],
  "🚭": ["no", "smoking"],
  "🚯": ["no", "littering"],
  "🚱": ["non", "potable", "water"],
  "🚷": ["no", "pedestrians"],
  "📵": ["no", "mobile", "phones"],
  "🔞": ["no", "one", "under", "eighteen"],
  "☢️": ["radioactive"],
  "☣️": ["biohazard"],

  // Common
  "👍": ["thumbs", "up", "like", "good", "yes"],
  "👎": ["thumbs", "down", "dislike", "bad", "no"],
  "❤️": ["red", "heart", "love", "like"],
  "💯": ["hundred", "points", "perfect", "score"],
  "🔥": ["fire", "flame", "hot"],
  "✨": ["sparkles", "sparkle", "magic"],
  "⭐": ["star", "favorite"],
  "💡": ["light", "bulb", "idea"],
  "🎉": ["party", "popper", "celebration"],
  "✅": ["check", "mark", "yes", "correct"],
  "❌": ["cross", "mark", "no", "wrong"],
  "⚠️": ["warning", "sign", "caution"],
  "💭": ["thought", "bubble", "thinking"],
  "🚀": ["rocket", "launch", "space"],
  "📝": ["memo", "note", "writing"],
  "🎯": ["target", "dart", "goal"],
  "💪": ["flexed", "biceps", "strong", "muscle"],
  "🙏": ["folded", "hands", "pray", "please"],
  "👏": ["clapping", "hands", "applause"],
  "🎊": ["confetti", "ball"],
  "🎈": ["balloon"],
  "🎁": ["wrapped", "gift"],
  "🎀": ["ribbon"],
  "🏆": ["trophy"],
  "🥇": ["1st", "place", "medal", "gold"],
  "🥈": ["2nd", "place", "medal", "silver"],
  "🥉": ["3rd", "place", "medal", "bronze"],
  "🏅": ["sports", "medal"],
  "🎖️": ["military", "medal"],
  "🎗️": ["reminder", "ribbon"],
  "🎫": ["ticket"],
  "🎟️": ["admission", "tickets"],
  "🎪": ["circus", "tent"],
  "🎭": ["performing", "arts"],
  "🎨": ["artist", "palette"],
  "🎬": ["clapper", "board"],
  "🎤": ["microphone", "mic"],
  "🎧": ["headphone"],
  "🎼": ["musical", "score"],
  "🎹": ["piano", "keyboard"],
  "🥁": ["drum"],
  "🎷": ["saxophone"],
  "🎺": ["trumpet"],
  "🎸": ["guitar"],
  "🎻": ["violin"],
  "🎲": ["dice", "game"],
  "🎯": ["target", "dart", "goal"],
  "🎳": ["bowling"],
  "🎮": ["video", "game", "controller"],
  "🎰": ["slot", "machine"],
};

